### ISSUE TITLE
Station list blank

### ISSUE THREAD

**Issue by mochman** [cowboysdude/MMM-GAS#3]
Looks like the website changed the way it formatted the fuel data.  I am sending you a pull request that fixes it.  I also added a couple more features:

You can now get fuel data for regular (default), mid-grade, premium, and diesel.  I also threw in a way to sort by price or distance (default).  I saw you had an items variable in the default config section as well.  I assume that was to only show X number of items.  I added that to your for loop that iterates through the gas array.

**Comment by cowboysdude** [comment]
Thank you!
